___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)


1.19.2


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [4]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [5]:
number = 0
np.full((5, 5), number)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:**

In [6]:
A = np.random.randint(20, size = (1,21))
A

array([[15,  6,  5,  8,  3,  9, 15,  8,  3,  1,  3,  5, 12,  2,  6,  8,
         7, 16,  4, 10,  3]])

In [7]:
# индекс нулевого элемента
A[0][9]

1

In [8]:
# индекс ненулевых элементов
A[0][0:8]

array([15,  6,  5,  8,  3,  9, 15,  8])

In [9]:
# индекс ненулевых элементов
A[0][10:21]

array([ 3,  5, 12,  2,  6,  8,  7, 16,  4, 10,  3])

**Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:**

In [51]:
#медиана

np.mean(A)

-0.5

In [52]:
#Стандартное отклонение

np.std(A)

5.678908345800274

**Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:**

In [61]:
B = np.random.randint(50, size = (4,2))
C = np.random.randint(50, size = (2,2))

Получили следующие матрицы

In [62]:
B

array([[33, 20],
       [32, 14],
       [18,  3],
       [ 3, 23]])

In [63]:
C

array([[36, 23],
       [31, 31]])

In [64]:
#Меняем форму матрицы С и умножаем на матрицу В
F = np.reshape(C, (4,1)) * B
F

array([[1188,  720],
       [ 736,  322],
       [ 558,   93],
       [  93,  713]])

**Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення.**

Максимальне значення замінити на 0:

In [65]:
D = np.reshape(F, (1,8))
D

array([[1188,  720,  736,  322,  558,   93,   93,  713]])

In [66]:
np.max(D)

1188

In [67]:
D[0][5] = 0
D

array([[1188,  720,  736,  322,  558,    0,   93,  713]])

**Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:**

In [75]:
np.corrcoef(F, rowvar=False)

array([[1.        , 0.06131903],
       [0.06131903, 1.        ]])

In [70]:
F[0]

array([1188,  720])

**Дано матрицю. Знайти ранг матриці:**

In [54]:

a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [55]:
from numpy import linalg as LA

#Ранг матрицы
LA.matrix_rank(a)

3

**Знайти визначник матриці:**

In [56]:
LA.det(a)

440.0000000000002

**найти власні значення та власні вектори матриці: **

In [22]:
wa, va = LA.eigh(a)

In [23]:
wa #собственные числа матрицы а

array([-14.30540864,  -4.34740072,  23.65280936])

In [24]:
va #собственные векторы матрицы а

array([[ 0.15315575,  0.88160309,  0.44645191],
       [ 0.63674998, -0.43353159,  0.6376518 ],
       [-0.75570681, -0.18661821,  0.62775861]])

**Знайдіть число, що найчастіше зустрічається в масиві:**

In [27]:
a = np.random.randint(0,10,50)

In [34]:
a

array([2, 7, 3, 3, 7, 3, 3, 7, 1, 0, 4, 8, 9, 6, 4, 0, 7, 1, 5, 3, 8, 6,
       0, 7, 2, 6, 9, 2, 6, 2, 6, 4, 4, 2, 6, 0, 0, 5, 6, 9, 6, 5, 5, 0,
       3, 4, 4, 8, 0, 1])

In [32]:
np.argmax(np.bincount(a))

6

**Виведіть лише парні числа, що діляться на 5:**

In [41]:
#если вывести из массива а, который выше, то кроме 0 и 5(которое не парное) ничего не получится, поскольку массив до 10

a = np.random.randint(0,10,50)
l = [i for i in a if i%5 == 0]
print(*l)

5 0 0 0 0 5 0 5 5 0 5


**Розв'яжіть систему рівнянь:**
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

**Составим систему матриц для поиска решения уровнения**

In [43]:
A = [[2, 5], [1, -10]]
#X = [[x], [y]]
B = [[1], [3]]

**Находим матрицу, обратную матрице А**


In [45]:
#создаем массив
A_A = np.array(A)
inv_A = np.linalg.inv(A_A)
print(inv_A)

[[ 0.4   0.2 ]
 [ 0.04 -0.08]]


**Находим Произведение матрицы В и обратной матрице А**


In [47]:
B_B = np.array(B)
X = np.linalg.inv(A_A).dot(B_B)
print(*X)

[1.] [-0.2]


**Проверяем:**

In [49]:
2*1 + 5*(-0.2)

1.0

In [50]:
1 - 10*(-0.2)

3.0